FROM eclipse-temurin:17
LABEL mentainer = "namraniilyas@gmail.com"
WORKDIR /app
COPY target/equipement-service-0.0.1-SNAPSHOT.jar /app/equipement-service.jar
ENTRYPOINT ["java" , "-jar" , "equipement-service.jar"]